### ISSUE TITLE
JS/CSS files not found

### ISSUE THREAD

**Issue by dominicjprice** [ktg/databox-container-manager#5]
I'm able to launch the container manager successfully by following the instructions, if I load the index page in a browser though I get 404 errors for:
styles/databox.css
templates/app-list.js
templates/app-store.js

Is there something I am doing wrong?

**Comment by Toshbrown** [comment]
Have you run the build scripts? Have a look in the package.json file

**Comment by dominicjprice** [comment]
Not sure, do I need to do ``npm build``? I've done ``npm install --production``.

**Comment by Toshbrown** [comment]
Try
npm install --devlopment -g
npm run build

If that dose not work try running the commands manually.

**Comment by dominicjprice** [comment]
Cool, thanks 👍

**Comment by dominicjprice** [comment]
That worked thank you after I also installed the pug and riot Node packages.
